
#define TRANSPORT_NOTIFICATION_HEARTBEAT	DECLARE_EVENT_ID(TRANSPORT_SUBSYSTEM_PKM, TRANSPORT_PROTO_NOTIFICATIONS, 1) // generic heartbeat notification
#define TRANSPORT_EVENT_ALERT			DECLARE_EVENT_ID(TRANSPORT_SUBSYSTEM_PKM, TRANSPORT_PROTO_EVENTS, 1) // generic error alert
#define TRANSPORT_REQUEST_PROC			DECLARE_EVENT_ID(TRANSPORT_SUBSYSTEM_PKM, TRANSPORT_PROTO_REQUESTS, 1) // process request


#define TRANSPORT_EVENT_PING			DECLARE_EVENT_ID(TRANSPORT_SUBSYSTEM_TEST, TRANSPORT_PROTO_NOTIFICATIONS, 1) // ping event
#define TRANSPORT_EVENT_PONG			DECLARE_EVENT_ID(TRANSPORT_SUBSYSTEM_TEST, TRANSPORT_PROTO_NOTIFICATIONS, 2) // ping replay
#define TRANSPORT_EVENT_DEBUG			DECLARE_EVENT_ID(TRANSPORT_SUBSYSTEM_TEST, TRANSPORT_PROTO_NOTIFICATIONS, 3) // debug control event

