

/*
	Global list of all subsystems
*/

#define TRANSPORT_SUBSYSTEM_COMMON	0
#define TRANSPORT_SUBSYSTEM_SORM1	1
#define TRANSPORT_SUBSYSTEM_SORM2	2
#define TRANSPORT_SUBSYSTEM_PRIHD	3
#define TRANSPORT_SUBSYSTEM_PKV		4
#define TRANSPORT_SUBSYSTEM_PKM		5
#define TRANSPORT_SUBSYSTEM_SORD	6
#define TRANSPORT_SUBSYSTEM_PPK		7
#define TRANSPORT_SUBSYSTEM_PAD		8
#define TRANSPORT_SUBSYSTEM_PTO		9
#define TRANSPORT_SUBSYSTEM_PD		10
#define TRANSPORT_SUBSYSTEM_PRPD	11
#define TRANSPORT_SUBSYSTEM_GEO		12
#define TRANSPORT_SUBSYSTEM_PASD	13
#define TRANSPORT_SUBSYSTEM_PGO		14
#define TRANSPORT_SUBSYSTEM_TIME	15
#define TRANSPORT_SUBSYSTEM_TEST	16 // for internal usage
#define TRANSPORT_SUBSYSTEM_BPED	17
#define TRANSPORT_SUBSYSTEM_TFOP	18
#define TRANSPORT_SUBSYSTEM_TOB		19
#define TRANSPORT_SUBSYSTEM_SORM3	20
#define TRANSPORT_SUBSYSTEM_SORM4	21
#define TRANSPORT_SUBSYSTEM_AVR		22 // audio-video recorders
