
/*
	List of general data codes
*/

#define TRANSPORT_DATA_ERROR_CODE	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_DWORD, 100) // generic error code

#define TRANSPORT_DATA_LARGE_SIZE	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_QWORD, 110) // generic large size
#define TRANSPORT_DATA_LARGE_OFFSET	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_QWORD, 111) // generic large offset
#define TRANSPORT_DATA_LARGE_CONTENTS	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_ARRAY_BYTE, 112) // data contents for large transfer
#define TRANSPORT_DATA_LARGE_BUF_SIZE	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_DWORD, 113) // suggested large buffer size

#define TRANSPORT_DATA_PROCESS_ID	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_DWORD, 120) // ID of a process
#define TRANSPORT_DATA_PROCESS_NAME	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_STRING, 121) // name of a process
#define TRANSPORT_DATA_PROCESS_PATH	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_STRING, 122) // name of a process with path
#define TRANSPORT_DATA_PROCESS_HOST	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_STRING, 123) // name of a host
#define TRANSPORT_DATA_PROCESS_WDIR	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_STRING, 124) // current work dir of a process
#define TRANSPORT_DATA_PROCESS_MEMORY	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_QWORD, 130) // used memory
#define TRANSPORT_DATA_PROCESS_START_TIME	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_QWORD, 140) // process start timestamp
#define TRANSPORT_DATA_PROCESS_WALL_TIME	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_QWORD, 141) // process wall time interval
#define TRANSPORT_DATA_PROCESS_CPU_TIME	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_QWORD, 142) // process cpu time interval (kernel+user)
#define TRANSPORT_DATA_PROCESS_CPU_KTIME	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_QWORD, 143) // process cpu kernel time interval

#define TRANSPORT_PING_TIMESTAMP	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_TEST, TRANSPORT_DATA_QWORD, 1) // timestamp for ping/pong
#define TRANSPORT_PING_PAYLOAD		DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_TEST, TRANSPORT_ARRAY_BYTE, 1) // data contents for ping/pong


#define TRANSPORT_STAT_POINT_DATA	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_STRUCT, 200) // point statistical information
#define TRANSPORT_STAT_PEER_DATA	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_STRUCT, 201) // peer statistical information
#define TRANSPORT_STAT_HOST_DATA	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_STRUCT, 202) // host statistical information

#define TRANSPORT_STAT_POINT_ID		DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_DWORD,  210) // point ID
#define TRANSPORT_STAT_POINT_NAME	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_STRING, 211) // point name

#define TRANSPORT_STAT_TIME		DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_QWORD,  220) // stat time
#define TRANSPORT_STAT_TOTAL		DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_ARRAY_QWORD, 221) // total stat counters array

#define TRANSPORT_STAT_POINT_STATE	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_DWORD, 230) // point state
#define TRANSPORT_STAT_PEER_STATE	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_DWORD, 231) // peer state
#define TRANSPORT_STAT_HOST_STATE	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_DWORD, 232) // host state

#define TRANSPORT_STAT_LAST_ERROR	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_DWORD, 240) // last error code
#define TRANSPORT_STAT_ERROR_COUNT	DECLARE_DATA_ID(TRANSPORT_SUBSYSTEM_COMMON, TRANSPORT_DATA_DWORD, 241) // error count
